// <auto-generated />
using System;
using FitLead.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitLead.Infrastructure.Migrations
{
    [DbContext(typeof(FitLeadDbContext))]
    [Migration("20260524183007_AddWorkoutLogsModel")]
    partial class AddWorkoutLogsModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitLead.Domain.Invitations.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AcceptedByClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedByClientId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("TrainerId");

                    b.HasIndex("Status", "ExpiresAtUtc");

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("FitLead.Domain.Media.MediaAssets.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StorageObjectId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("StorageProvider")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("IX_media_assets_owner_user_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_media_assets_status");

                    b.HasIndex("StorageProvider", "StorageObjectId")
                        .IsUnique()
                        .HasDatabaseName("UX_media_assets_storage_provider_object_id");

                    b.ToTable("media_assets", null, t =>
                        {
                            t.HasCheckConstraint("CK_media_assets_duration_seconds_positive", "\"DurationSeconds\" IS NULL OR \"DurationSeconds\" > 0");

                            t.HasCheckConstraint("CK_media_assets_size_bytes_positive", "\"SizeBytes\" > 0");
                        });
                });

            modelBuilder.Entity("FitLead.Domain.Messenger.ChatMessages.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid?>("VideoReportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.HasIndex("VideoReportId")
                        .IsUnique()
                        .HasDatabaseName("UX_chat_messages_video_report_id")
                        .HasFilter("\"VideoReportId\" IS NOT NULL");

                    b.HasIndex("ChatId", "CreatedAtUtc")
                        .HasDatabaseName("IX_chat_messages_chat_id_created_at_utc");

                    b.HasIndex("ChatId", "Id")
                        .HasDatabaseName("IX_chat_messages_chat_id_id");

                    b.ToTable("chat_messages", null, t =>
                        {
                            t.HasCheckConstraint("CK_chat_messages_text_required_for_text_type", "\"Type\" <> 1 OR (\"Text\" IS NOT NULL AND length(btrim(\"Text\")) > 0)");

                            t.HasCheckConstraint("CK_chat_messages_video_report_id_null_for_text_type", "\"Type\" <> 1 OR \"VideoReportId\" IS NULL");

                            t.HasCheckConstraint("CK_chat_messages_video_report_shape", "\"Type\" <> 3 OR (\"VideoReportId\" IS NOT NULL AND \"Text\" IS NULL)");
                        });
                });

            modelBuilder.Entity("FitLead.Domain.Messenger.Chats.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastMessageAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("IX_chats_client_id");

                    b.HasIndex("TrainerId", "ClientId")
                        .IsUnique()
                        .HasDatabaseName("UX_chats_trainer_id_client_id");

                    b.ToTable("chats", (string)null);
                });

            modelBuilder.Entity("FitLead.Domain.Messenger.VideoReports.VideoReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TrainerFeedbackText")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChatId")
                        .HasDatabaseName("IX_video_reports_chat_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("IX_video_reports_client_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_video_reports_status");

                    b.HasIndex("TrainerId")
                        .HasDatabaseName("IX_video_reports_trainer_id");

                    b.ToTable("video_reports", (string)null);
                });

            modelBuilder.Entity("FitLead.Domain.Messenger.VideoReports.VideoReportMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderInReport")
                        .HasColumnType("integer");

                    b.Property<Guid>("VideoReportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MediaAssetId");

                    b.HasIndex("VideoReportId", "OrderInReport")
                        .IsUnique()
                        .HasDatabaseName("UX_video_report_media_report_id_order_in_report");

                    b.ToTable("video_report_media", null, t =>
                        {
                            t.HasCheckConstraint("CK_video_report_media_order_in_report_positive", "\"OrderInReport\" > 0");
                        });
                });

            modelBuilder.Entity("FitLead.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserId", "CreatedAtUtc")
                        .HasDatabaseName("IX_notifications_recipient_created");

                    b.HasIndex("RecipientUserId", "IsRead", "CreatedAtUtc")
                        .HasDatabaseName("IX_notifications_recipient_read_created");

                    b.HasIndex("SourceEventId", "RecipientUserId", "Type")
                        .IsUnique()
                        .HasDatabaseName("UX_notifications_source_event_recipient_type");

                    b.ToTable("notifications", null, t =>
                        {
                            t.HasCheckConstraint("CK_notifications_read_at_after_created", "\"ReadAtUtc\" IS NULL OR \"ReadAtUtc\" >= \"CreatedAtUtc\"");

                            t.HasCheckConstraint("CK_notifications_read_state_valid", "(\"IsRead\" = false AND \"ReadAtUtc\" IS NULL) OR (\"IsRead\" = true AND \"ReadAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_notifications_type_valid", "\"Type\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("FitLead.Domain.Notifications.PushSubscriptions.PushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique()
                        .HasDatabaseName("UX_push_subscriptions_endpoint");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_push_subscriptions_user_id");

                    b.HasIndex("UserId", "RevokedAtUtc")
                        .HasDatabaseName("IX_push_subscriptions_user_revoked");

                    b.ToTable("push_subscriptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_push_subscriptions_last_used_at_after_created", "\"LastUsedAtUtc\" IS NULL OR \"LastUsedAtUtc\" >= \"CreatedAtUtc\"");

                            t.HasCheckConstraint("CK_push_subscriptions_revoked_at_after_created", "\"RevokedAtUtc\" IS NULL OR \"RevokedAtUtc\" >= \"CreatedAtUtc\"");
                        });
                });

            modelBuilder.Entity("FitLead.Domain.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_outbox_messages_type");

                    b.HasIndex("Status", "NextRetryAtUtc", "OccurredAtUtc")
                        .HasDatabaseName("IX_outbox_messages_status_next_retry_occurred");

                    b.ToTable("outbox_messages", null, t =>
                        {
                            t.HasCheckConstraint("CK_outbox_messages_retry_count_non_negative", "\"RetryCount\" >= 0");

                            t.HasCheckConstraint("CK_outbox_messages_status_valid", "\"Status\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("FitLead.Domain.Trainings.Exercises.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CopiedFromExerciseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Equipment")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MediaAssetId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MuscleGroup")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OwnerTrainerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CopiedFromExerciseId");

                    b.HasIndex("Equipment");

                    b.HasIndex("MediaAssetId");

                    b.HasIndex("MuscleGroup");

                    b.HasIndex("OwnerTrainerId");

                    b.HasIndex("Source");

                    b.HasIndex("OwnerTrainerId", "CopiedFromExerciseId")
                        .IsUnique()
                        .HasFilter("\"CopiedFromExerciseId\" IS NOT NULL");

                    b.ToTable("exercises", null, t =>
                        {
                            t.HasCheckConstraint("CK_exercises_copied_from_trainer_only", "\"CopiedFromExerciseId\" IS NULL OR \"Source\" = 2");

                            t.HasCheckConstraint("CK_exercises_platform_owner_null", "\"Source\" <> 1 OR \"OwnerTrainerId\" IS NULL");

                            t.HasCheckConstraint("CK_exercises_trainer_owner_required", "\"Source\" <> 2 OR \"OwnerTrainerId\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("FitLead.Domain.Trainings.TrainingProgramAssignments.AssignedTrainingProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AccessSource")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrainingProgramId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainingProgramId")
                        .HasDatabaseName("IX_assigned_training_programs_training_program_id");

                    b.HasIndex("ClientId", "Status")
                        .HasDatabaseName("IX_assigned_training_programs_client_id_status");

                    b.HasIndex("ClientId", "TrainingProgramId")
                        .IsUnique()
                        .HasDatabaseName("UX_assigned_training_programs_active_client_program")
                        .HasFilter("\"Status\" = 1");

                    b.HasIndex("TrainerId", "ClientId")
                        .HasDatabaseName("IX_assigned_training_programs_trainer_id_client_id");

                    b.ToTable("assigned_training_programs", (string)null);
                });

            modelBuilder.Entity("FitLead.Domain.Trainings.TrainingPrograms.TrainingProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DaysPerWeek")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uuid");

                    b.Property<int>("WeeksCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("training_programs", null, t =>
                        {
                            t.HasCheckConstraint("CK_training_programs_days_per_week_range", "\"DaysPerWeek\" BETWEEN 1 AND 7");

                            t.HasCheckConstraint("CK_training_programs_weeks_count_range", "\"WeeksCount\" BETWEEN 1 AND 24");
                        });
                });

            modelBuilder.Entity("FitLead.Domain.Trainings.TrainingPrograms.TrainingProgramWorkout", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<int>("OrderInDay")
                        .HasColumnType("integer");

                    b.Property<Guid>("TrainingProgramId")
                        .HasColumnType("uuid");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.HasIndex("TrainingProgramId", "WeekNumber", "DayNumber", "OrderInDay");

                    b.ToTable("training_program_workouts", null, t =>
                        {
                            t.HasCheckConstraint("CK_training_program_workouts_day_number_positive", "\"DayNumber\" > 0");

                            t.HasCheckConstraint("CK_training_program_workouts_order_in_day_positive", "\"OrderInDay\" > 0");

                            t.HasCheckConstraint("CK_training_program_workouts_week_number_positive", "\"WeekNumber\" > 0");
                        });
                });

            modelBuilder.Entity("FitLead.Domain.Trainings.WorkoutLogs.WorkoutLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignedTrainingProgramId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DifficultyRating")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PerformedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrainingProgramWorkoutId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("IX_workout_logs_client_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_workout_logs_status");

                    b.HasIndex("TrainerId")
                        .HasDatabaseName("IX_workout_logs_trainer_id");

                    b.HasIndex("TrainingProgramWorkoutId");

                    b.HasIndex("AssignedTrainingProgramId", "TrainingProgramWorkoutId")
                        .IsUnique()
                        .HasDatabaseName("UX_workout_logs_assignment_program_workout");

                    b.ToTable("workout_logs", null, t =>
                        {
                            t.HasCheckConstraint("CK_workout_logs_completed_performed_at_required", "\"Status\" <> 1 OR \"PerformedAtUtc\" IS NOT NULL");

                            t.HasCheckConstraint("CK_workout_logs_difficulty_rating_range", "\"DifficultyRating\" IS NULL OR (\"DifficultyRating\" BETWEEN 1 AND 10)");

                            t.HasCheckConstraint("CK_workout_logs_skipped_fields_null", "\"Status\" <> 2 OR (\"PerformedAtUtc\" IS NULL AND \"DifficultyRating\" IS NULL)");

                            t.HasCheckConstraint("CK_workout_logs_status_valid", "\"Status\" IN (1, 2)");

                            t.HasCheckConstraint("CK_workout_logs_updated_at_after_created", "\"UpdatedAtUtc\" IS NULL OR \"UpdatedAtUtc\" >= \"CreatedAtUtc\"");
                        });
                });

            modelBuilder.Entity("FitLead.Domain.Trainings.Workouts.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("workouts", (string)null);
                });

            modelBuilder.Entity("FitLead.Domain.Trainings.Workouts.WorkoutExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("LoadKg")
                        .HasColumnType("numeric");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Repetitions")
                        .HasColumnType("integer");

                    b.Property<int>("RestSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("Sets")
                        .HasColumnType("integer");

                    b.Property<string>("TrainerNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.HasIndex("WorkoutId", "Order");

                    b.ToTable("workout_exercises", (string)null);
                });

            modelBuilder.Entity("FitLead.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FitLead.Infrastructure.Identity.AppIdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FitLead.Infrastructure.Persistence.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("ReasonRevoked")
                        .HasColumnType("text");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("IdentityUserId");

                    b.HasIndex("ReplacedByTokenId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("FitLead.Infrastructure.Persistence.Models.TrainerClient", b =>
                {
                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TrainerId", "ClientId");

                    b.HasIndex("ClientId");

                    b.HasIndex("TrainerId");

                    b.ToTable("trainer_clients", (string)null);
                });

            modelBuilder.Entity("FitLead.Infrastructure.Persistence.Models.UserIdentityLink", b =>
                {
                    b.Property<Guid>("DomainUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DomainUserId");

                    b.HasIndex("IdentityUserId")
                        .IsUnique();

                    b.ToTable("user_identity_links", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FitLead.Domain.Invitations.Invitation", b =>
                {
                    b.HasOne("FitLead.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AcceptedByClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FitLead.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FitLead.Domain.Media.MediaAssets.MediaAsset", b =>
                {
                    b.HasOne("FitLead.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FitLead.Domain.Messenger.ChatMessages.ChatMessage", b =>
                {
                    b.HasOne("FitLead.Domain.Messenger.Chats.Chat", null)
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitLead.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitLead.Domain.Messenger.VideoReports.VideoReport", null)
                        .WithMany()
                        .HasForeignKey("VideoReportId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FitLead.Domain.Messenger.Chats.Chat", b =>
                {
                    b.HasOne("FitLead.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitLead.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FitLead.Domain.Messenger.VideoReports.VideoReport", b =>
                {
                    b.HasOne("FitLead.Domain.Messenger.Chats.Chat", null)
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitLead.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitLead.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FitLead.Domain.Messenger.VideoReports.VideoReportMedia", b =>
                {
                    b.HasOne("FitLead.Domain.Media.MediaAssets.MediaAsset", null)
                        .WithMany()
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitLead.Domain.Messenger.VideoReports.VideoReport", null)
                        .WithMany("Media")
                        .HasForeignKey("VideoReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitLead.Domain.Notifications.Notification", b =>
                {
                    b.HasOne("FitLead.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FitLead.Domain.Notifications.PushSubscriptions.PushSubscription", b =>
                {
                    b.HasOne("FitLead.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FitLead.Domain.Trainings.Exercises.Exercise", b =>
                {
                    b.HasOne("FitLead.Domain.Trainings.Exercises.Exercise", null)
                        .WithMany()
                        .HasForeignKey("CopiedFromExerciseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FitLead.Domain.Media.MediaAssets.MediaAsset", null)
                        .WithMany()
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FitLead.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerTrainerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FitLead.Domain.Trainings.TrainingProgramAssignments.AssignedTrainingProgram", b =>
                {
                    b.HasOne("FitLead.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitLead.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitLead.Domain.Trainings.TrainingPrograms.TrainingProgram", null)
                        .WithMany()
                        .HasForeignKey("TrainingProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FitLead.Domain.Trainings.TrainingPrograms.TrainingProgram", b =>
                {
                    b.HasOne("FitLead.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FitLead.Domain.Trainings.TrainingPrograms.TrainingProgramWorkout", b =>
                {
                    b.HasOne("FitLead.Domain.Trainings.TrainingPrograms.TrainingProgram", null)
                        .WithMany("Workouts")
                        .HasForeignKey("TrainingProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitLead.Domain.Trainings.Workouts.Workout", null)
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FitLead.Domain.Trainings.WorkoutLogs.WorkoutLog", b =>
                {
                    b.HasOne("FitLead.Domain.Trainings.TrainingProgramAssignments.AssignedTrainingProgram", null)
                        .WithMany()
                        .HasForeignKey("AssignedTrainingProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitLead.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitLead.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitLead.Domain.Trainings.TrainingPrograms.TrainingProgramWorkout", null)
                        .WithMany()
                        .HasForeignKey("TrainingProgramWorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitLead.Domain.Trainings.Workouts.Workout", b =>
                {
                    b.HasOne("FitLead.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FitLead.Domain.Trainings.Workouts.WorkoutExercise", b =>
                {
                    b.HasOne("FitLead.Domain.Trainings.Exercises.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitLead.Domain.Trainings.Workouts.Workout", null)
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitLead.Infrastructure.Persistence.Models.RefreshToken", b =>
                {
                    b.HasOne("FitLead.Infrastructure.Identity.AppIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FitLead.Infrastructure.Persistence.Models.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("FitLead.Infrastructure.Persistence.Models.TrainerClient", b =>
                {
                    b.HasOne("FitLead.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitLead.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FitLead.Infrastructure.Persistence.Models.UserIdentityLink", b =>
                {
                    b.HasOne("FitLead.Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("FitLead.Infrastructure.Persistence.Models.UserIdentityLink", "DomainUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FitLead.Infrastructure.Identity.AppIdentityUser", null)
                        .WithOne()
                        .HasForeignKey("FitLead.Infrastructure.Persistence.Models.UserIdentityLink", "IdentityUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FitLead.Infrastructure.Identity.AppIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FitLead.Infrastructure.Identity.AppIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitLead.Infrastructure.Identity.AppIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FitLead.Infrastructure.Identity.AppIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitLead.Domain.Messenger.VideoReports.VideoReport", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("FitLead.Domain.Trainings.TrainingPrograms.TrainingProgram", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("FitLead.Domain.Trainings.Workouts.Workout", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
